### ISSUE TITLE
Visual changes

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DT-Local-viewer#1]
Please make the following changes:
- Remove the "3D Tile Inspector"
- Remove the Cesium icons and text from the bottom of the viewer and replace with the same as in the Asset viewer page.
- Do not display the globe.
- Do not display terrain or imagery
- All assets should be displayed at 0,0 coordinates, just like all in the asset viewer. Even if asset if already geo-referenced, also display it at 0,0.
- All assets should be have the save grey background as in the asset viewer.

![image](https://user-images.githubusercontent.com/13057505/120466599-4025c200-c36d-11eb-884d-af8a05d68f52.png)

![image](https://user-images.githubusercontent.com/13057505/120467182-e4a80400-c36d-11eb-815c-3383bca4f018.png)

**Comment by 3DGISKing** [comment]
Would the tileset be geo-referenced or not?

**Comment by Construkted-Reality** [comment]
Because we don't know what tilesets the end user will be using, both goe-referenced and NOT geo-referenced tiles should have the same behavior.
Both should display on a grey background and not display the globe/terrain/imagery/etc

**Comment by 3DGISKing** [comment]
understand

**Comment by 3DGISKing** [comment]
please check
