### ISSUE TITLE
Starts up in developer mode.

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DT-Local-viewer#10]
3D Tile viewer starts up with developer mode enabled.
Please fix, and create a new release

![image](https://user-images.githubusercontent.com/13057505/152345968-bd347b28-0063-4a06-b2e4-f6ec00eb2192.png)

**Comment by 3DGISKing** [comment]
yeah

**Comment by 3DGISKing** [comment]
I have just downloaded 1.0.4 and tested it but could not see what you mentioned.

**Comment by Construkted-Reality** [comment]
You are correct. 
I must have used an older version.
