### ISSUE TITLE
Error on loading tileset.json generated UltraMesh 1.6.7

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DT-Local-viewer#11]
The viewer is showing an error on loading tilesets from newer version of UltraMesh.

Can you please update the local-viewer to correctly display the asset?

Use this file to test:
https://s3.us-east-2.wasabisys.com/construkted-test/3d_tiles-test3.zip

Unzip and you will find 2 foledrs:
**tiles.1.6.2B** is an older version of UltraMesh which loads and displays correctly in the 3d local viewer
**tiles.1.6.7** is the newest version of UltraMesh and shows the error.

![image](https://user-images.githubusercontent.com/13057505/198306299-b988846e-40ac-439e-bd89-f6172a58030b.png)

**Comment by 3DGISKing** [comment]
yes

**Comment by 3DGISKing** [comment]
should I generate exe file?

**Comment by 3DGISKing** [comment]
please check

**Comment by Construkted-Reality** [comment]
works
