### ISSUE TITLE
Measure buttons

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DT-Local-viewer#4]
The measurement buttons are only clickable when the mouse pointer is on the top 1/3 of the button.
When the mouse pointer is on the lower 2/3 of the button, they are not clickable.

![Buttons](https://user-images.githubusercontent.com/13057505/120926314-58b61500-c6aa-11eb-8a25-d80a35864e6b.gif)

**Comment by 3DGISKing** [comment]
fixed
