### ISSUE TITLE
3d tile gives error

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DT-Local-viewer#6]
When I try to load this 3d tile into 3D Local Viewer, I get an error message.
Can you please investigate?

https://s3.us-east-2.wasabisys.com/construkted-uploads/admin/atcasiuerpk-LOD.zip

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/121979621-1a60da00-cdbd-11eb-8d03-eebab4e0c053.png)
fixed

**Comment by Construkted-Reality** [comment]
What was the problem?

**Comment by 3DGISKing** [comment]
missing necessary class.
please see this.
https://github.com/Construkted-Reality/3DT-Local-viewer/commit/315f4a930fd2ea26483d7624bcc29ceb21a3f0ad

**Comment by Construkted-Reality** [comment]
Please update the RELEASED version with this change

**Comment by 3DGISKing** [comment]
done
